---
- name: Create the DB.
  command: > 
    {{ drush_path }} sql-create -y
    chdir={{ drupal_core_path }}
  become: no

- name: Import mysql DB.
  command: >
    mysql -u {{ drupal_db_user }} -p{{ drupal_db_password }} drupal -e "source /home/{{ vagrant_user }}/db/database.sql"
  notify: restart webserver
  become: no